# Data Settings
phase: valid

guidance_method: 'wavelet'
dilation_rates: (1, 2, 3, 4)
# dj
vae_model: tiny_vae # or tiny_vae
pickle_file_path: ./Dataset/bus/bus_train_test_names.pkl

# model_weight: './ckpt/provided_models/valid_bus/best_model.pth' # ./ckpt/tinyvae_baseline_bus_correct_scaling/epochs_1000/checkpoints/provided_model_717.pth
# snapshot_path: ./ckpt/provided_models/valid_bus/valid_busi_provided_model
# save_seg_img_path: ./ckpt/provided_models/valid_bus/predicted_masks_provided_model

model_weight: ./ckpt/tinyvae_baseline_bus_sft_wavelet_no_approx/epochs_1000/checkpoints/best_valid_loss_rec_392.pth
snapshot_path: ./ckpt/tinyvae_baseline_bus_sft_wavelet_no_approx/epochs_1000/valid_bus_best_valid_loss_rec
save_seg_img_path: ./ckpt/tinyvae_baseline_bus_sft_wavelet_no_approx/epochs_1000/best_valid_loss_rec_predicted_masks

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# dice Settings
w_rec: 1
