# Data Settings
phase: valid

patchify: False
learn_patch: False

guidance_method: 'wavelet'
dilation_rates: (1, 2, 3, 4)

vae_model: tiny_vae # or tiny_vae
pickle_file_path: ./Dataset/busi/busi_train_test_names.pkl

model_weight: ./ckpt/tinyvae-sft-lmm/epoch_1500/checkpoints/best_valid_dice_242.pth
snapshot_path: ./ckpt/tinyvae-sft-lmm/epoch_1500/valid_busi_best_valid_dice_test
save_seg_img_path: ./ckpt/tinyvae-sft-lmm/epoch_1500/predicted_masks_best_valid_dice_test

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# dice Settings
w_rec: 1
