# [CHANGED] --> We add the config file for kvasir-seg valid

# Data Settings
phase: valid
pickle_file_path: ./Dataset/Kvasir-SEG/kvasir-seg_train_test_names.pkl
model_weight: ./ckpt/tiny_vae_kvasir-seg/202506222225/checkpoints/best_valid_loss_dice.pth
snapshot_path: ./ckpt/tiny_vae_kvasir-seg/202506222225/valid_kvasir-seg_best_valid_loss
save_seg_img_path: ./ckpt/tiny_vae_kvasir-seg/202506222225/predicted_masks_best_valid_loss

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# Loss Settings [CHANGED] --> Note how we dont have dice loss as we dont have access to the ground truth in the valid phase
w_rec: 1
