# Data Settings
phase: valid
pickle_file_path: ./Dataset/kvasir-instrument/kvasir_train_test_names.pkl
model_weight: ./ckpt/tiny_vae_kvasir-instrument/best_valid_dice.pth
snapshot_path: ./ckpt/tiny_vae_kvasir-instrument/202506200123/valid_kvasir-instrument_best_valid_dice
save_seg_img_path: ./ckpt/tiny_vae_kvasir-instrument/202506200123/predicted_masks_best_valid_dice

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# Loss Settings
w_rec: 1
