# Data Settings
phase: valid

guidance_method: 'wavelet'
dilation_rates: (1, 2, 3, 4)
# fj
vae_model: tiny_vae # or tiny_vae
pickle_file_path: ./Dataset/kvasir-instrument/kvasir-instrument_train_test_names.pkl

model_weight: ./ckpt/tiny_vae_baseline_kvasir-instrument_sft_wavelet_28_x_28_original_settings/epochs_1000/checkpoints/best_valid_dice_620.pth
snapshot_path: ./ckpt/tiny_vae_baseline_kvasir-instrument_sft_wavelet_28_x_28_original_settings/epochs_1000/valid_best_valid_dice
save_seg_img_path: ./ckpt/tiny_vae_baseline_kvasir-instrument_sft_wavelet_28_x_28_original_settings/epochs_1000/predicted_masks_best_valid_dice

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# loss_rec Settings
w_rec: 1
