# Data Settings
phase: valid

guidance_method: False
dilation_rates: (1, 2, 3, 4)
# dj
vae_model: litevae-s # or tiny_vae

pickle_file_path: ./Dataset/QaTar-19/QaTar_19_train_val_test_names.pkl
model_weight: ./ckpt/litevae_baseline_qatar_align_loss_new_settings/epochs_500/checkpoints/best_valid_dice_456.pth
snapshot_path: ./ckpt/litevae_baseline_qatar_align_loss_new_settings/epochs_500/valid_qatar-19_best_valid_dice_test
save_seg_img_path: ./ckpt/litevae_baseline_qatar_align_loss_new_settings/epochs_500/predicted_masks_best_valid_dice_test

# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# Loss Settings
w_rec: 1
