# Data Settings
phase: valid
# pickle_file_path: ./Dataset/busi/busi_train_test_names.pkl
# model_weight: ./ckpt/busi/202506201608/checkpoints/latent_mapping_model_epoch_0200.pth
# snapshot_path: ./ckpt/busi/202506201608/valid_busi_epoch_0200
# save_seg_img_path: ./ckpt/busi/202506201608/predicted_masks_0200

pickle_file_path: ./Dataset/busi/busi_train_test_names.pkl
model_weight: ./ckpt/tiny_vae_busi/202506211320/checkpoints/best_valid_dice.pth
snapshot_path: ./ckpt/tiny_vae_busi/202506211320/valid_busi_best_valid_dice
save_seg_img_path: ./ckpt/tiny_vae_busi/202506211320/predicted_masks_best_valid_dice


# Valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# Loss Settings
w_rec: 1
w_kl: 0.001
