# [CHANGED] --> We add the config file for kvasir-seg train

# Data Settings
phase: train
pickle_file_path: ./Dataset/Kvasir-SEG/kvasir-seg_train_test_names.pkl
snapshot_path: ./ckpt/tiny_vae_kvasir-seg

# Training Settings
epochs: 2000 # [CHANGED] from 1000
GPUs: [0]
num_workers: 8
batch_size: 24 # [CHANGED] from 8
save_freq: 100
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1, 2, 4, 4]

# Optimizer Settings
lr: 0.002

# Loss Settings [CHANGED] --> weights for the reconstruction loss (i.e. latent loss in SDSEG) and dice loss
w_rec: 1
w_dice: 1
